### ISSUE TITLE
Integrated development environment

### ISSUE THREAD

**Issue by alejoseb** [DoHelloWorld/stm32f3_Modbus_Slave_UART-DMA-FreeRTOS#1]
Hi,
I would like to try your modbus library. It seems a very interesting project using DMA.  
Can you provide some hints about compiling the code? 
Do you use any particular IDE?  
Any help will be appreciated.
Thanks in advance.

**Comment by DoHelloWorld** [comment]
Hi, this code compiled in EmBitz IDE with GCC
